import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import{getFirestore,collection,query,orderBy,getDocs,doc,setDoc,deleteDoc,updateDoc,getDoc}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import{getAuth,signInWithEmailAndPassword,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import{getStorage,ref,uploadBytes,getDownloadURL,deleteObject}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-storage.js";
import{firebaseConfig}from"./firebase-config.js";
const app=initializeApp(firebaseConfig),db=getFirestore(app),auth=getAuth(app),storage=getStorage(app),$=s=>document.querySelector(s),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));let editing=null,admin=null;
$("#loginForm").onsubmit=async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,$("#email").value,$("#password").value)}catch(x){$("#loginStatus").textContent=x.message}};
onAuthStateChanged(auth,async u=>{admin=u;if(!u){$("#loginCard").classList.remove("hidden");$("#adminApp").classList.add("hidden");$("#logout").classList.add("hidden");return}const t=await u.getIdTokenResult(true);if(t.claims.admin!==true){$("#loginStatus").textContent="This account is not an administrator.";await signOut(auth);return}$("#loginCard").classList.add("hidden");$("#adminApp").classList.remove("hidden");$("#logout").classList.remove("hidden");loadAll()});
$("#logout").onclick=()=>signOut(auth);$("#cancelEdit").onclick=clearForm;$("#memoryForm").onsubmit=saveMemory;
async function saveMemory(e){e.preventDefault();const st=$("#memoryStatus");st.textContent="Saving…";try{const id=$("#memoryId").value||crypto.randomUUID();let url=editing?.mediaUrl||"",path=editing?.storagePath||"",type=editing?.mediaType||"";const file=$("#media").files[0];if(file){if(file.size>250*1024*1024)throw Error("File is larger than 250 MB.");type=file.type.startsWith("video/")?"video":"image";const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");path=`memories/${id}/${Date.now()}_${safe}`;await uploadBytes(ref(storage,path),file,{contentType:file.type,customMetadata:{ownerUid:admin.uid}});url=await getDownloadURL(ref(storage,path));if(editing?.storagePath&&editing.storagePath!==path)try{await deleteObject(ref(storage,editing.storagePath))}catch{}}await setDoc(doc(db,"memories",id),{title:$("#title").value.trim(),description:$("#description").value.trim(),dateLabel:$("#dateLabel").value.trim(),dateSort:$("#dateSort").value,category:$("#category").value,published:$("#published").checked,mediaUrl:url,storagePath:path,mediaType:type,updatedAt:new Date().toISOString(),updatedBy:admin.uid},{merge:true});st.textContent="Saved successfully. ✨";clearForm();loadMemories()}catch(x){console.error(x);st.textContent=x.message||"Save failed."}}
async function loadAll(){loadMemories();loadWishes()}
async function loadMemories(){const root=$("#memoryAdmin");root.textContent="Loading…";const s=await getDocs(query(collection(db,"memories"),orderBy("dateSort","asc")));root.innerHTML="";s.forEach(d=>{const m=d.data(),el=document.createElement("div");el.className="admin-memory";el.innerHTML=`${m.mediaUrl?(m.mediaType==="video"?`<video src="${esc(m.mediaUrl)}" muted></video>`:`<img src="${esc(m.mediaUrl)}">`):"🖼️"}<div><strong>${esc(m.title)}</strong><div>${esc(m.dateLabel)} · ${m.published?"Published":"Draft"}</div><small>${esc(m.description).slice(0,140)}</small></div><div class="actions"><button class="btn ghost" data-edit="${d.id}">Edit</button> <button class="danger" data-del="${d.id}">Delete</button></div>`;root.append(el)});root.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>editMemory(b.dataset.edit));root.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>removeMemory(b.dataset.del))}
async function editMemory(id){const d=await getDoc(doc(db,"memories",id));editing={id,...d.data()};$("#memoryId").value=id;$("#title").value=editing.title||"";$("#description").value=editing.description||"";$("#dateLabel").value=editing.dateLabel||"";$("#dateSort").value=editing.dateSort||"";$("#category").value=editing.category||"Family";$("#published").checked=editing.published!==false;scrollTo({top:0,behavior:"smooth"})}
async function removeMemory(id){if(!confirm("Delete this memory and its media?"))return;const d=await getDoc(doc(db,"memories",id)),m=d.data();if(m?.storagePath)try{await deleteObject(ref(storage,m.storagePath))}catch{}await deleteDoc(doc(db,"memories",id));loadMemories()}
function clearForm(){editing=null;$("#memoryForm").reset();$("#memoryId").value="";$("#published").checked=true}
async function loadWishes(){const root=$("#wishesAdmin");root.textContent="Loading…";const s=await getDocs(query(collection(db,"wishes"),orderBy("createdAt","desc")));root.innerHTML="";s.forEach(d=>{const w=d.data(),el=document.createElement("article");el.className="wish";el.innerHTML=`<strong>${esc(w.name)}</strong><p>${esc(w.text)}</p><button class="btn primary" data-a="${d.id}">${w.approved?"Approved":"Approve"}</button> <button class="danger" data-w="${d.id}">Delete</button>`;root.append(el)});root.querySelectorAll("[data-a]").forEach(b=>b.onclick=async()=>{await updateDoc(doc(db,"wishes",b.dataset.a),{approved:true});loadWishes()});root.querySelectorAll("[data-w]").forEach(b=>b.onclick=async()=>{if(confirm("Delete this wish?")){await deleteDoc(doc(db,"wishes",b.dataset.w));loadWishes()}})}
