import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import{getFirestore,collection,query,where,orderBy,limit,getDocs,addDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import{getAuth,signInAnonymously,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import{firebaseConfig}from"./firebase-config.js";

const app=initializeApp(firebaseConfig),db=getFirestore(app),auth=getAuth(app);
const $=s=>document.querySelector(s);let user=null;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const toast=m=>{const t=$("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2500)};
onAuthStateChanged(auth,u=>user=u);signInAnonymously(auth).catch(console.warn);
setTimeout(()=>$("#intro")?.classList.add("hide"),1500);
$("#menuBtn").onclick=()=>$("#drawer").classList.toggle("open");
document.querySelectorAll("#drawer a").forEach(a=>a.onclick=()=>$("#drawer").classList.remove("open"));

async function memories(){const root=$("#memoryTimeline");try{
const s=await getDocs(query(collection(db,"memories"),where("published","==",true),orderBy("dateSort","asc"),limit(100)));root.innerHTML="";
if(s.empty){root.innerHTML='<article class="memory"><div class="memory-body"><h3>The story is waiting…</h3><p>Add Dibora’s first memory from the private admin editor.</p></div></article>';return}
s.forEach(d=>{const m=d.data(),el=document.createElement("article");el.className="memory";el.innerHTML=`<span class="memory-dot"></span>${m.mediaUrl?(m.mediaType==="video"?`<video class="memory-media" src="${esc(m.mediaUrl)}" controls playsinline preload="metadata"></video>`:`<img class="memory-media" src="${esc(m.mediaUrl)}" alt="${esc(m.title)}" loading="lazy">`):""}<div class="memory-body"><div class="memory-meta">${esc(m.dateLabel)}</div><h3>${esc(m.title)}</h3><p>${esc(m.description)}</p></div>`;root.append(el)})}catch(e){console.error(e);root.innerHTML='<article class="memory"><div class="memory-body"><h3>Memory archive unavailable</h3><p>Check Firebase configuration, rules and indexes.</p></div></article>'}}
async function wishes(){const root=$("#wishList");try{const s=await getDocs(query(collection(db,"wishes"),where("approved","==",true),orderBy("createdAt","desc"),limit(30)));root.innerHTML=s.empty?'<article class="wish"><strong>Be the first.</strong><p>Dibora’s wall is waiting for your words.</p></article>':"";s.forEach(d=>{const w=d.data(),el=document.createElement("article");el.className="wish";el.innerHTML=`<strong>${esc(w.name)}</strong><p>${esc(w.text)}</p>`;root.append(el)})}catch(e){console.error(e)}}
$("#wishForm").onsubmit=async e=>{e.preventDefault();$("#wishStatus").textContent="Sending…";try{if(!user)await signInAnonymously(auth);await addDoc(collection(db,"wishes"),{name:$("#wishName").value.trim(),text:$("#wishText").value.trim(),approved:false,authorUid:user.uid,createdAt:serverTimestamp()});e.target.reset();$("#wishStatus").textContent="Saved for approval. ❤️"}catch(err){$("#wishStatus").textContent="Could not save the wish."}};
const stars=JSON.parse(localStorage.getItem("dibora-stars")||"[]"),sky=$("#sky");function star(text){const s=document.createElement("span");s.className="star";s.textContent="✦";s.title=text;s.style.left=5+Math.random()*90+"%";s.style.bottom=5+Math.random()*20+"%";sky.append(s)}stars.forEach(star);$("#skyForm").onsubmit=e=>{e.preventDefault();const x=$("#skyWish").value.trim();if(!x)return;stars.push(x);localStorage.setItem("dibora-stars",JSON.stringify(stars.slice(-80)));star(x);e.target.reset()};
$("#capsuleText").value=localStorage.getItem("dibora-capsule")||"";$("#saveCapsule").onclick=()=>{const x=$("#capsuleText").value.trim();if(x){localStorage.setItem("dibora-capsule",x);$("#capsuleStatus").textContent="Sealed for the future. 💛"}};

let audioCtx,timer,playing=false;const notes=[261.63,261.63,293.66,261.63,349.23,329.63,261.63,293.66,392,349.23];
function tone(f,d=.22){audioCtx??=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=f;o.type="sine";g.gain.value=.05;o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}
function music(){if(playing){clearInterval(timer);playing=false;$("#melodyState").textContent="PAUSED";$("#melodyBtn").textContent="▶"}else{let i=0;timer=setInterval(()=>tone(notes[i++%notes.length]),270);playing=true;$("#melodyState").textContent="PLAYING";$("#melodyBtn").textContent="Ⅱ"}}
$("#melodyBtn").onclick=music;$("#musicBtn").onclick=music;document.querySelectorAll("#piano button").forEach(b=>b.onclick=()=>tone(+b.dataset.note,.35));

const games={balloon(){const p=$("#gamePanel");p.innerHTML='<h3>Balloon Pop</h3><p>Pop as many as possible in 30 seconds.</p><div class="balloon-board" id="board"></div><p>Score: <b id="score">0</b> · Time: <b id="time">30</b>s</p><button class="btn primary" id="start">Start</button>';$("#start").onclick=()=>{let sc=0,t=30,board=$("#board");const sp=setInterval(()=>{const b=document.createElement("button");b.className="balloon";b.textContent="🎈";b.style.left=Math.random()*90+"%";b.onclick=()=>{sc++;$("#score").textContent=sc;b.remove()};board.append(b);setTimeout(()=>b.remove(),3900)},450);const cl=setInterval(()=>{t--;$("#time").textContent=t;if(t<=0){clearInterval(sp);clearInterval(cl);toast(`Score: ${sc} 🎈`)}},1000)}},quiz(){const qs=[["What does Dibora deserve most?",["Love & blessings","Cold coffee","More homework"]],["What should never disappear?",["Her smile","Her battery","The weekend"]],["A perfect birthday contains…",["Memories","An empty box","Dust"]]];let i=0,score=0;const render=()=>{const q=qs[i];$("#gamePanel").innerHTML=`<div class="quiz-card"><p>Question ${i+1}/${qs.length}</p><h3>${q[0]}</h3><div class="quiz-options">${q[1].map((x,n)=>`<button data-n="${n}">${x}</button>`).join("")}</div></div>`;document.querySelectorAll(".quiz-options button").forEach(b=>b.onclick=()=>{if(+b.dataset.n===0)score++;i++;if(i<qs.length)render();else{$("#gamePanel").innerHTML=`<div class="quiz-card"><h3>🎉 ${score}/${qs.length}</h3><p>${score===qs.length?"You know her perfectly!":"There is always more to discover."}</p><button class="btn primary" id="again">Play again</button></div>`;$("#again").onclick=games.quiz}})};render()},memory(){const vals=["🌸","⭐","🎓","✈️","💝","🎂"],deck=[...vals,...vals].sort(()=>Math.random()-.5);let first=null,lock=false,pairs=0,moves=0;$("#gamePanel").innerHTML=`<p>Find all six pairs.</p><div class="match-grid">${deck.map((_,i)=>`<button class="match-card" data-i="${i}">✦</button>`).join("")}</div><p>Pairs: <b id="pairs">0</b>/6 · Moves: <b id="moves">0</b></p>`;const cards=[...document.querySelectorAll(".match-card")];cards.forEach((c,i)=>c.onclick=()=>{if(lock||c.classList.contains("revealed"))return;c.textContent=deck[i];c.classList.add("revealed");if(first===null){first=i;return}moves++;$("#moves").textContent=moves;if(deck[first]===deck[i]){pairs++;$("#pairs").textContent=pairs;first=null;if(pairs===6)toast("Every pair found! 💖")}else{lock=true;setTimeout(()=>{cards[first].textContent="✦";cards[i].textContent="✦";cards[first].classList.remove("revealed");cards[i].classList.remove("revealed");first=null;lock=false},650)}})}};
document.querySelectorAll(".game-tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".game-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");games[b.dataset.game]()});games.balloon();

const canvas=$("#fireworks"),ctx=canvas.getContext("2d");function size(){canvas.width=canvas.clientWidth*devicePixelRatio;canvas.height=canvas.clientHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}size();addEventListener("resize",size);
$("#fireworksBtn").onclick=()=>{const ps=[];for(let k=0;k<7;k++){const x=canvas.clientWidth*(.15+Math.random()*.7),y=canvas.clientHeight*(.1+Math.random()*.45);for(let i=0;i<40;i++){const a=Math.random()*6.28,s=1+Math.random()*4;ps.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,l:1})}}function run(){ctx.clearRect(0,0,canvas.clientWidth,canvas.clientHeight);ps.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.035;p.l-=.012;ctx.globalAlpha=Math.max(p.l,0);ctx.fillStyle="#e4b74c";ctx.fillRect(p.x,p.y,2,2)});ctx.globalAlpha=1;if(ps.some(p=>p.l>0))requestAnimationFrame(run)}run();toast("Happy Birthday, Dibora! ✨")};
memories();wishes();
